### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by LWJerri** [Ayfri/discord-fetch-messages#16]
Hello! This package doesn't work on discord.js v`^13.7.0`. Can you fix it, please? 

@Ayfri

**Comment by Ayfri** [comment]
What doesn't work exactly ? Can you explain more precisely the problem please ?

**Comment by LWJerri** [comment]
When I write
```ts
import Fetcher from "discord-fetch-messages";

const fetcher = new Fetcher(bot);
```

I get error:
![image](https://user-images.githubusercontent.com/50290430/168331662-a2a44084-e597-4712-8c0e-cec7aa74fa39.png)

But also if I set 
```ts
import { Fetcher } from "discord-fetch-messages";

const fetcher = new Fetcher(bot);
```

I get new error:
![image](https://user-images.githubusercontent.com/50290430/168331777-2e7e3559-524c-4129-bb74-2e3cf4696769.png)


Full code to reproduce the error:
```ts
import "source-map-support/register";
import { Client } from "discord.js";
import { Fetcher } from "discord-fetch-messages";

const bot = new Client({ intents: ["GUILDS", "GUILD_MESSAGES"] });

const fetcher = new Fetcher(bot);

bot.on("ready", async () => {
  const guildMessages = await fetcher.fetchGuild("GUILD_ID");

  console.log(guildMessages);
});

bot.login("BOT_TOKEN");
```

**Comment by LWJerri** [comment]
Hello. Idk how, but I delete `node_modules` and `yarn.lock` install discord.js@latest, and the error was resolved.

**Comment by Ayfri** [comment]
Ah, new typings from discord are breaking the library, I'll fix it when I have time to.

**Comment by Ayfri** [comment]
Sorry it's taking longer than planned for me to get time to work on this, in mid-August I should have time.

**Comment by schellenbergk** [comment]
done yet?

**Comment by Ayfri** [comment]
Hi, I just published 2.5.0, can you try it ? I also moved to ESModules, but it's the first time I use them, so I'm not sure that it will work directly.

**Comment by LWJerri** [comment]
Hi. I tested it on `discord.js@13.12.0` and it works. Thanks.

**Comment by Ayfri** [comment]
Great !
